### ISSUE TITLE
Is there a way to change the view?

### ISSUE THREAD

**Issue by nakulbende** [vincep5/MMM-Beestat#1]
Can I choose what view I want. Currently, it is the runtime summary. Can I get the runtime detail view?

![image](https://user-images.githubusercontent.com/8712050/71729093-d702ed80-2e0c-11ea-8778-1666a6cde766.png)

**Comment by vincep5** [comment]
No, that graphing is pretty advanced.  I could offer other types of simple graphs.  I need to re-look at what the API offers, as it has changed since I first made the module for MM.

**Comment by nakulbende** [comment]
Hey ,

thanks a lot for the reply. This module is awesome. Can you make a
simplified version of that graph? just two lines/ bar graphs trailing set
and measured temperature?

thanks,



Nakul Bende,

Materials Scientist, Formlabs Inc.

http://nakulbende.com


- Ever tried. Ever failed. Try Again. Fail again. Fail better.

--Samuel Beckett
